name: Code Check
on: [push]

jobs:
  code-check:
    name: Code-Check
    strategy:
      matrix:
        php: [7.3]
    runs-on: ubuntu-latest
    container:
      image: php:${{ matrix.php }}-apache
      env:
        NODE_ENV: production
      ports:
      - 80
      volumes:
      - $GITHUB_WORKSPACE:/var/www/html
    steps:
    - name: Set up container
      run: |
        echo "Update package lists."
        apt-get update
        echo "Install base packages."
        apt-get install -y build-essential libssl-dev gnupg libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libicu-dev libxml2-dev vim wget unzip git subversion default-mysql-client
        echo "Add yarn package repository."
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
        echo "Update package lists."
        apt-get update
        echo "Install NVM."
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
        . ~/.nvm/nvm.sh
        echo "Install node."
        nvm install 12.9.0
        nvm use 12.9.0
        echo "Install yarn."
        apt-get install -y yarn
        echo "Install composer."
        curl -sS https://getcomposer.org/installer | php 
        mv composer.phar /usr/local/bin/composer
        echo "Install PHP extensions."
        docker-php-ext-install -j$(nproc) iconv intl xml soap opcache pdo pdo_mysql mysqli mbstring
        docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
        docker-php-ext-install -j$(nproc) gd
        pecl install mcrypt-1.0.2
        docker-php-ext-enable mcrypt
    - name: Checkout Repository
      uses: actions/checkout@v1

    - name: Run composer install
      run: |
        composer install -vvv --profile --prefer-dist --dev